global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'kafka'
    scrape_interval: 5s
    static_configs:
    - targets:
      - 'kafka1:1234'
      - 'kafka2:1234'
      labels:
        env: 'dev'

  - job_name: 'zookeeper'
    scrape_interval: 5s
    static_configs:
    - targets:
      - 'zookeeper:1234'
      labels:
        env: 'dev'

  - job_name: 'producer'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'producer:1234'
        labels:
          env: 'dev'

  - job_name: 'consumer'
    scrape_interval: 5s
    static_configs:
      - targets:
          - "consumer:1234"
        labels:
          env: 'dev'

  - job_name: 'kafka-lag-exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'kafka-lag-exporter:9999'
        labels:
           env: 'dev'
